version: "3.7"
services:
  splunk:
    image: splunk/splunk:7.0.3
    hostname: splunk
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_USER: root
      SPLUNK_ENABLE_LISTEN: 9997
      SPLUNK_PASSWORD: password
      SPLUNK_ADD: tcp 1514
    volumes:
      - opt-splunk-etc:/opt/splunk/etc
      - opt-splunk-var:/opt/splunk/var
    ports:
      - "8000:8000"
      - "9997:9997"
      - "8088:8088"
      - "1514:1514"

volumes:
  opt-splunk-etc:
  opt-splunk-var: