version: "3.7"
services:
  service-registry:
    image: fixparser/service-registry
    build: ../fix-parser-service-registry/service-registry-app
    ports:
      - 9060:9060
      - 8761:8761
    environment:
      LOGGING_FILE: /logs/application.log
    volumes:
      - log_volume:/logs

  splunkforwarder:
    image: splunk/universalforwarder:7.3.3
    hostname: splunkforwarder
    environment:
      SPLUNK_START_ARGS: --accept-license --answer-yes
      SPLUNK_STANDALONE_URL: splunk:9997
      SPLUNK_USER: root
      SPLUNK_ADD: monitor /logs
      SPLUNK_PASSWORD: password
    restart: always
    volumes:
      - log_volume:/logs

volumes:
  log_volume: